services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: literature-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env  

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: literature-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
